using ACT.DataModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace ACT.Services.OPERA.Mapper
{
    public class Map_OPERA_REPORT_SUN_DETAIL : IMap_OPERA_REPORT_SUN_DERAIL
    {
        public DataTable Map(DataTable operaReport, List<OPERA_REPORT_SUN_DETAIL_Model> oPERA_REPORT_SUN_DETAIL_s, int PSTG_HDR_ID)
        {
            DataTable sunDetailResult = new DataTable();

            foreach (OPERA_REPORT_SUN_DETAIL_Model c in oPERA_REPORT_SUN_DETAIL_s)
            {

                sunDetailResult.Columns.Add(new DataColumn(columnName: c.SunAttribute, dataType: System.Type.GetType(c.ValueType, true, true)));

            }

            int LINE_NUM = 0;
            foreach (DataRow operaReportRow in operaReport.Rows)
            {
                DataRow dataRow = operaReport.NewRow();

                LINE_NUM++;

                foreach (DataColumn dataColumn in sunDetailResult.Columns)
                {
                    string columnName = dataColumn.ColumnName;
                    OPERA_REPORT_SUN_DETAIL_Model oPERA_REPORT_SUN_DETAIL = oPERA_REPORT_SUN_DETAIL_s.Find(x => x.SunAttribute == columnName);
                    if (oPERA_REPORT_SUN_DETAIL.IsConst)
                    {
                        // TODO - Complete all the cases
                        if (oPERA_REPORT_SUN_DETAIL.ValueType == "string")
                        {
                            dataRow[columnName] = oPERA_REPORT_SUN_DETAIL.StringValue;

                        }
                        else if (oPERA_REPORT_SUN_DETAIL.ValueType == "int")
                        {
                            dataRow[columnName] = oPERA_REPORT_SUN_DETAIL.IntValue;
                        }
                    }
                    else if (oPERA_REPORT_SUN_DETAIL.AutoGenerated)
                    {
                        if(oPERA_REPORT_SUN_DETAIL.SunAttribute == "PSTG_HDR_ID")
                        {
                            dataRow[columnName] = PSTG_HDR_ID;
                        }
                        else if(oPERA_REPORT_SUN_DETAIL.SunAttribute == "LINE_NUM")
                        {
                            dataRow[columnName] = LINE_NUM;
                        }
                    }
                    else
                    {
                        dataRow[columnName] = operaReportRow[oPERA_REPORT_SUN_DETAIL.MapWithOPERA];
                    }
                }
            }

            return sunDetailResult;
        }

    }
}
