using ACT.DataModels;
using ACT.Services.ApiDbAccess.OPERA_SUN;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ACT.Controllers
{
    [ApiController]
    [Route("Mapping/OperaToSun/ReportToDetail")]
    [EnableCors("MyPolicy")]
    public class Mapping_OPERA_REPORT_TO_SUN_DETAIL : ControllerBase
    {
        private IOPERA_REPORT_SUN_DETAIL _oPERA_REPORT_SUN_DETAIL;
        public class OPERA_REPORT_SUN_DETAIL_ViewModel
        {
            public int Id { get; set; }

            [Required]
            public string SunAttribute { get; set; }
            [Required]
            public bool IsConst { get; set; }
            [Required]
            public bool AutoGenerated { get; set; }
            [Required]
            public string ValueType { get; set; }
            public string StringValue { get; set; }
            public int? IntValue { get; set; }

            public short? ShortValue { get; set; }

            public DateTime? DateTimeValue { get; set; }

            public decimal? DecimalValue { get; set; }

            public double? DoubleValue { get; set; }

            public string MapWithOPERA { get; set; }
        }

        public class OPERA_REPORT_SUN_DETAIL_InsertModel
        {
            [Required]
            public string SunAttribute { get; set; }
            [Required]
            public bool IsConst { get; set; }
            [Required]
            public bool AutoGenerated { get; set; }
            [Required]
            public string ValueType { get; set; }
            public string StringValue { get; set; }
            public int? IntValue { get; set; }

            public short? ShortValue { get; set; }

            public DateTime? DateTimeValue { get; set; }

            public decimal? DecimalValue { get; set; }

            public double? DoubleValue { get; set; }

            public string MapWithOPERA { get; set; }
        }

        public Mapping_OPERA_REPORT_TO_SUN_DETAIL(IOPERA_REPORT_SUN_DETAIL oPERA_REPORT_SUN_DETAIL)
        {
            this._oPERA_REPORT_SUN_DETAIL = oPERA_REPORT_SUN_DETAIL;
        }

        [HttpGet("GetOperaReportSunDetail")]
        public List<OPERA_REPORT_SUN_DETAIL_ViewModel> GetOperaReportSunDetail()
        {
            List<OPERA_REPORT_SUN_DETAIL_ViewModel> oPERA_REPORT_SUN_DETAIL_ViewModels = new List<OPERA_REPORT_SUN_DETAIL_ViewModel>();

            foreach (OPERA_REPORT_SUN_DETAIL_Model o in _oPERA_REPORT_SUN_DETAIL.Get_OPERA_REPORT_SUN_DETAIL_s())
            {
                OPERA_REPORT_SUN_DETAIL_ViewModel oPERA_REPORT_SUN_DETAIL_ViewModel = new OPERA_REPORT_SUN_DETAIL_ViewModel()
                {
                    Id = o.Id,
                    SunAttribute = o.SunAttribute,
                    IsConst = o.IsConst,
                    AutoGenerated = o.AutoGenerated,
                    ValueType = o.ValueType,
                    StringValue = o.StringValue,
                    IntValue = o.IntValue,
                    ShortValue = o.ShortValue,
                    DateTimeValue = o.DateTimeValue,
                    DecimalValue = o.DecimalValue,
                    DoubleValue = o.DoubleValue,
                    MapWithOPERA = o.MapWithOPERA

                };
                oPERA_REPORT_SUN_DETAIL_ViewModels.Add(oPERA_REPORT_SUN_DETAIL_ViewModel);
            }

            return oPERA_REPORT_SUN_DETAIL_ViewModels;
        }

        [HttpPost("UpdateOperaReportSunDetail")]
        public async Task UpdateOperaReportSunDetail(List<OPERA_REPORT_SUN_DETAIL_ViewModel> oPERA_REPORT_SUN_DETAIL_ViewModels)
        {
            List<OPERA_REPORT_SUN_DETAIL_Model> oPERA_REPORT_SUN_DETAIL_s = new List<OPERA_REPORT_SUN_DETAIL_Model>();

            foreach (OPERA_REPORT_SUN_DETAIL_ViewModel o in oPERA_REPORT_SUN_DETAIL_ViewModels)
            {
                OPERA_REPORT_SUN_DETAIL_Model oPERA_REPORT_SUN_DETAIL = new OPERA_REPORT_SUN_DETAIL_Model()
                {
                    SunAttribute = o.SunAttribute,
                    IsConst = o.IsConst,
                    AutoGenerated = o.AutoGenerated,
                    ValueType = o.ValueType,
                    StringValue = o.StringValue,
                    IntValue = o.IntValue,
                    ShortValue = o.ShortValue,
                    DateTimeValue = o.DateTimeValue,
                    DecimalValue = o.DecimalValue,
                    DoubleValue = o.DoubleValue,
                    MapWithOPERA = o.MapWithOPERA

                };
                oPERA_REPORT_SUN_DETAIL_s.Add(oPERA_REPORT_SUN_DETAIL);
            }
            await _oPERA_REPORT_SUN_DETAIL.Update_OPERA_REPORT_SUN_DETAIL(oPERA_REPORT_SUN_DETAIL_s);
        }

       

        [HttpPost("InsertRow")]
        public async Task InsertRow(OPERA_REPORT_SUN_DETAIL_InsertModel oPERA_REPORT_SUN_DETAIL_InsertModel)
        {
            OPERA_REPORT_SUN_DETAIL_Model oPERA_REPORT_SUN_DETAIL_Model = new OPERA_REPORT_SUN_DETAIL_Model()
            {
                SunAttribute = oPERA_REPORT_SUN_DETAIL_InsertModel.SunAttribute,
                IsConst = oPERA_REPORT_SUN_DETAIL_InsertModel.IsConst,
                AutoGenerated = oPERA_REPORT_SUN_DETAIL_InsertModel.AutoGenerated,
                ValueType = oPERA_REPORT_SUN_DETAIL_InsertModel.ValueType,
                StringValue = oPERA_REPORT_SUN_DETAIL_InsertModel.StringValue,
                IntValue = oPERA_REPORT_SUN_DETAIL_InsertModel.IntValue,
                ShortValue = oPERA_REPORT_SUN_DETAIL_InsertModel.ShortValue,
                DateTimeValue = oPERA_REPORT_SUN_DETAIL_InsertModel.DateTimeValue,
                DecimalValue = oPERA_REPORT_SUN_DETAIL_InsertModel.DecimalValue,
                DoubleValue = oPERA_REPORT_SUN_DETAIL_InsertModel.DoubleValue,
                MapWithOPERA = oPERA_REPORT_SUN_DETAIL_InsertModel.MapWithOPERA
            };
            await _oPERA_REPORT_SUN_DETAIL.InsertRow(oPERA_REPORT_SUN_DETAIL_Model);
        }

        [HttpPatch("UpdateRow")]
        public async Task UpdateRow(OPERA_REPORT_SUN_DETAIL_ViewModel oPERA_REPORT_SUN_DETAIL_ViewModel)
        {
            OPERA_REPORT_SUN_DETAIL_Model oPERA_REPORT_SUN_DETAIL_Model = new OPERA_REPORT_SUN_DETAIL_Model()
            {
                Id = oPERA_REPORT_SUN_DETAIL_ViewModel.Id,
                SunAttribute = oPERA_REPORT_SUN_DETAIL_ViewModel.SunAttribute,
                IsConst = oPERA_REPORT_SUN_DETAIL_ViewModel.IsConst,
                AutoGenerated = oPERA_REPORT_SUN_DETAIL_ViewModel.AutoGenerated,
                ValueType = oPERA_REPORT_SUN_DETAIL_ViewModel.ValueType,
                StringValue = oPERA_REPORT_SUN_DETAIL_ViewModel.StringValue,
                IntValue = oPERA_REPORT_SUN_DETAIL_ViewModel.IntValue,
                ShortValue = oPERA_REPORT_SUN_DETAIL_ViewModel.ShortValue,
                DateTimeValue = oPERA_REPORT_SUN_DETAIL_ViewModel.DateTimeValue,
                DecimalValue = oPERA_REPORT_SUN_DETAIL_ViewModel.DecimalValue,
                DoubleValue = oPERA_REPORT_SUN_DETAIL_ViewModel.DoubleValue,
                MapWithOPERA = oPERA_REPORT_SUN_DETAIL_ViewModel.MapWithOPERA
            };
            await _oPERA_REPORT_SUN_DETAIL.UpdateRow(oPERA_REPORT_SUN_DETAIL_Model);
        }

        [HttpDelete("DeleteRow")]
        public async Task DeleteRow(int Id)
        {
            await _oPERA_REPORT_SUN_DETAIL.DeleteRow(Id);
        }

        [HttpPost("LoadDefaults")]
        public async Task LoadDefaults()
        {

            await _oPERA_REPORT_SUN_DETAIL.LoadDefaults();
        }
    }
}
