using ACT.DataModels;
using ACT.Services.ApiDbAccess.OPERA_SUN;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ACT.Controllers
{
    [ApiController]
    [Route("Mapping/OperaToSun/ReportToDetail")]
    [EnableCors("MyPolicy")]
    public class Mapping_OPERA_REPORT_TO_SUN_DETAIL : ControllerBase
    {
        private IOPERA_REPORT_SUN_DETAIL _oPERA_REPORT_SUN_DETAIL;
        public class OPERA_REPORT_SUN_DETAIL_ViewModel
        {
            public int Id { get; set; }

            [Required]
            public string SunAttribute { get; set; }
            [Required]
            public bool IsConst { get; set; }
            [Required]
            public bool AutoGenerated { get; set; }
            [Required]
            public string ValueType { get; set; }
            public int? IntValue { get; set; }

            public short? ShortValue { get; set; }

            public DateTime? DateTimeValue { get; set; }

            public decimal? DecimalValue { get; set; }

            public double? DoubleValue { get; set; }

            public string MapWithOPERA { get; set; }
        }

        public Mapping_OPERA_REPORT_TO_SUN_DETAIL(IOPERA_REPORT_SUN_DETAIL oPERA_REPORT_SUN_DETAIL)
        {
            this._oPERA_REPORT_SUN_DETAIL = oPERA_REPORT_SUN_DETAIL;
        }

        [HttpGet("GetOperaReportSunDetail")]
        public List<OPERA_REPORT_SUN_DETAIL_ViewModel> GetOperaReportSunDetail()
        {
            List<OPERA_REPORT_SUN_DETAIL_ViewModel> oPERA_REPORT_SUN_DETAIL_ViewModels = new List<OPERA_REPORT_SUN_DETAIL_ViewModel>();

            foreach (OPERA_REPORT_SUN_DETAIL_Model o in _oPERA_REPORT_SUN_DETAIL.Get_OPERA_REPORT_SUN_DETAIL_s())
            {
                OPERA_REPORT_SUN_DETAIL_ViewModel oPERA_REPORT_SUN_DETAIL_ViewModel = new OPERA_REPORT_SUN_DETAIL_ViewModel()
                {
                    Id = o.Id,
                    SunAttribute = o.SunAttribute,
                    IsConst = o.IsConst,
                    AutoGenerated = o.AutoGenerated,
                    ValueType = o.ValueType,
                    IntValue = o.IntValue,
                    ShortValue = o.ShortValue,
                    DateTimeValue = o.DateTimeValue,
                    DecimalValue = o.DecimalValue,
                    DoubleValue = o.DoubleValue,
                    MapWithOPERA = o.MapWithOPERA

                };
                oPERA_REPORT_SUN_DETAIL_ViewModels.Add(oPERA_REPORT_SUN_DETAIL_ViewModel);
            }

            return oPERA_REPORT_SUN_DETAIL_ViewModels;
        }

        [HttpPost("UpdateOperaReportSunDetail")]
        public async Task UpdateOperaReportSunDetail(List<OPERA_REPORT_SUN_DETAIL_ViewModel> oPERA_REPORT_SUN_DETAIL_ViewModels)
        {
            List<OPERA_REPORT_SUN_DETAIL_Model> oPERA_REPORT_SUN_DETAIL_s = new List<OPERA_REPORT_SUN_DETAIL_Model>();

            foreach (OPERA_REPORT_SUN_DETAIL_ViewModel o in oPERA_REPORT_SUN_DETAIL_ViewModels)
            {
                OPERA_REPORT_SUN_DETAIL_Model oPERA_REPORT_SUN_HDR = new OPERA_REPORT_SUN_DETAIL_Model()
                {
                    SunAttribute = o.SunAttribute,
                    IsConst = o.IsConst,
                    AutoGenerated = o.AutoGenerated,
                    ValueType = o.ValueType,
                    IntValue = o.IntValue,
                    ShortValue = o.ShortValue,
                    DateTimeValue = o.DateTimeValue,
                    DecimalValue = o.DecimalValue,
                    DoubleValue = o.DoubleValue,
                    MapWithOPERA = o.MapWithOPERA

                };
                oPERA_REPORT_SUN_DETAIL_s.Add(oPERA_REPORT_SUN_HDR);
            }
            await _oPERA_REPORT_SUN_DETAIL.Update_OPERA_REPORT_SUN_DETAIL(oPERA_REPORT_SUN_DETAIL_s);
        }


        [HttpPost("LoadDefaults")]
        public async Task LoadDefaults()
        {

            await _oPERA_REPORT_SUN_DETAIL.LoadDefaults();
        }
    }
}
