using Microsoft.EntityFrameworkCore.Migrations;

namespace ACT.Migrations.ApiDbMigrations
{
    public partial class EditDMs : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "ValueType",
                table: "OPERA_REPORT_SUN_HDRS",
                type: "TEXT",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "TEXT",
                oldNullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "AutoGenerated",
                table: "OPERA_REPORT_SUN_HDRS",
                type: "INTEGER",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AlterColumn<string>(
                name: "ValueType",
                table: "OPERA_REPORT_SUN_DETAILS",
                type: "TEXT",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "TEXT",
                oldNullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "AutoGenerated",
                table: "OPERA_REPORT_SUN_DETAILS",
                type: "INTEGER",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AlterColumn<string>(
                name: "ValueType",
                table: "HRMS_REPORT_SUN_HDRS",
                type: "TEXT",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "TEXT",
                oldNullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "AutoGenerated",
                table: "HRMS_REPORT_SUN_HDRS",
                type: "INTEGER",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AlterColumn<string>(
                name: "ValueType",
                table: "HRMS_REPORT_SUN_DETAILS",
                type: "TEXT",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "TEXT",
                oldNullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "AutoGenerated",
                table: "HRMS_REPORT_SUN_DETAILS",
                type: "INTEGER",
                nullable: false,
                defaultValue: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "AutoGenerated",
                table: "OPERA_REPORT_SUN_HDRS");

            migrationBuilder.DropColumn(
                name: "AutoGenerated",
                table: "OPERA_REPORT_SUN_DETAILS");

            migrationBuilder.DropColumn(
                name: "AutoGenerated",
                table: "HRMS_REPORT_SUN_HDRS");

            migrationBuilder.DropColumn(
                name: "AutoGenerated",
                table: "HRMS_REPORT_SUN_DETAILS");

            migrationBuilder.AlterColumn<string>(
                name: "ValueType",
                table: "OPERA_REPORT_SUN_HDRS",
                type: "TEXT",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "TEXT");

            migrationBuilder.AlterColumn<string>(
                name: "ValueType",
                table: "OPERA_REPORT_SUN_DETAILS",
                type: "TEXT",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "TEXT");

            migrationBuilder.AlterColumn<string>(
                name: "ValueType",
                table: "HRMS_REPORT_SUN_HDRS",
                type: "TEXT",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "TEXT");

            migrationBuilder.AlterColumn<string>(
                name: "ValueType",
                table: "HRMS_REPORT_SUN_DETAILS",
                type: "TEXT",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "TEXT");
        }
    }
}
