using ACT.DataModels;
using ACT.Services.ApiDbAccess.HRMS_SUN;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ACT.Controllers
{
    [ApiController]
    [Route("Mapping/HrmsToSun/ReportToDetail")]
    [EnableCors("MyPolicy")]
    public class Mapping_HRMS_REPORT_TO_SUN_DETAIL : ControllerBase
    {
        private IHRMS_REPORT_SUN_DETAIL _hRMS_REPORT_SUN_DETAIL;

        public class HRMS_REPORT_SUN_DETAIL_ViewModel
        {
            public int Id { get; set; }

            [Required]
            public string SunAttribute { get; set; }
            [Required]
            public bool IsConst { get; set; }
            [Required]
            public bool AutoGenerated { get; set; }
            [Required]
            public string ValueType { get; set; }
            public string StringValue { get; set; }
            public int? IntValue { get; set; }

            public short? ShortValue { get; set; }

            public DateTime? DateTimeValue { get; set; }

            public decimal? DecimalValue { get; set; }

            public double? DoubleValue { get; set; }

            public string MapWithHRMS { get; set; }
        }

        public class HRMS_REPORT_SUN_DETAIL_InsertModel
        {

            [Required]
            public string SunAttribute { get; set; }
            [Required]
            public bool IsConst { get; set; }
            [Required]
            public bool AutoGenerated { get; set; }
            [Required]
            public string ValueType { get; set; }
            public string StringValue { get; set; }

            public int? IntValue { get; set; }

            public short? ShortValue { get; set; }

            public DateTime? DateTimeValue { get; set; }

            public decimal? DecimalValue { get; set; }

            public double? DoubleValue { get; set; }

            public string MapWithHRMS { get; set; }
        }


        public Mapping_HRMS_REPORT_TO_SUN_DETAIL(IHRMS_REPORT_SUN_DETAIL hRMS_REPORT_SUN_DETAIL)
        {
            this._hRMS_REPORT_SUN_DETAIL = hRMS_REPORT_SUN_DETAIL;
        }

        [HttpGet("GetHrmsReportSunDETAIL")]
        public List<HRMS_REPORT_SUN_DETAIL_ViewModel> GetHrmsReportSunDETAIL()
        {
            List<HRMS_REPORT_SUN_DETAIL_ViewModel> HRMS_REPORT_SUN_DETAIL_ViewModels = new List<HRMS_REPORT_SUN_DETAIL_ViewModel>();

            foreach (HRMS_REPORT_SUN_DETAIL_Model o in _hRMS_REPORT_SUN_DETAIL.Get_HRMS_REPORT_SUN_DETAIL_s())
            {
                HRMS_REPORT_SUN_DETAIL_ViewModel HRMS_REPORT_SUN_DETAIL_ViewModel = new HRMS_REPORT_SUN_DETAIL_ViewModel()
                {
                    Id = o.Id,
                    SunAttribute = o.SunAttribute,
                    IsConst = o.IsConst,
                    AutoGenerated = o.AutoGenerated,
                    ValueType = o.ValueType,
                    StringValue = o.StringValue,
                    IntValue = o.IntValue,
                    ShortValue = o.ShortValue,
                    DateTimeValue = o.DateTimeValue,
                    DecimalValue = o.DecimalValue,
                    DoubleValue = o.DoubleValue,
                    MapWithHRMS = o.MapWithHRMS
                };
                HRMS_REPORT_SUN_DETAIL_ViewModels.Add(HRMS_REPORT_SUN_DETAIL_ViewModel);
            }

            return HRMS_REPORT_SUN_DETAIL_ViewModels;
        }

        [HttpPost("UpdateHrmsReportSunDETAIL")]
        public async Task UpdateHrmsReportSunDETAIL(List<HRMS_REPORT_SUN_DETAIL_ViewModel> HRMS_REPORT_SUN_DETAIL_ViewModels)
        {
            List<HRMS_REPORT_SUN_DETAIL_Model> hRMS_REPORT_SUN_DETAIL_s = new List<HRMS_REPORT_SUN_DETAIL_Model>();

            foreach (HRMS_REPORT_SUN_DETAIL_ViewModel o in HRMS_REPORT_SUN_DETAIL_ViewModels)
            {
                HRMS_REPORT_SUN_DETAIL_Model hRMS_REPORT_SUN_DETAIL = new HRMS_REPORT_SUN_DETAIL_Model()
                {
                    SunAttribute = o.SunAttribute,
                    IsConst = o.IsConst,
                    AutoGenerated = o.AutoGenerated,
                    ValueType = o.ValueType,
                    StringValue = o.StringValue,
                    IntValue = o.IntValue,
                    ShortValue = o.ShortValue,
                    DateTimeValue = o.DateTimeValue,
                    DecimalValue = o.DecimalValue,
                    DoubleValue = o.DoubleValue,
                    MapWithHRMS = o.MapWithHRMS
                };
                       hRMS_REPORT_SUN_DETAIL_s.Add(hRMS_REPORT_SUN_DETAIL);
            }
            await _hRMS_REPORT_SUN_DETAIL.Update_HRMS_REPORT_SUN_DETAIL(hRMS_REPORT_SUN_DETAIL_s);
        }

        [HttpPost("InsertRow")]
        public async Task InsertRow(HRMS_REPORT_SUN_DETAIL_InsertModel HRMS_REPORT_SUN_DETAIL_InsertModel)
        {
            HRMS_REPORT_SUN_DETAIL_Model HRMS_REPORT_SUN_DETAIL_Model = new HRMS_REPORT_SUN_DETAIL_Model()
            {
                SunAttribute = HRMS_REPORT_SUN_DETAIL_InsertModel.SunAttribute,
                IsConst = HRMS_REPORT_SUN_DETAIL_InsertModel.IsConst,
                AutoGenerated = HRMS_REPORT_SUN_DETAIL_InsertModel.AutoGenerated,
                ValueType = HRMS_REPORT_SUN_DETAIL_InsertModel.ValueType,
                StringValue = HRMS_REPORT_SUN_DETAIL_InsertModel.StringValue,
                IntValue = HRMS_REPORT_SUN_DETAIL_InsertModel.IntValue,
                ShortValue = HRMS_REPORT_SUN_DETAIL_InsertModel.ShortValue,
                DateTimeValue = HRMS_REPORT_SUN_DETAIL_InsertModel.DateTimeValue,
                DecimalValue = HRMS_REPORT_SUN_DETAIL_InsertModel.DecimalValue,
                DoubleValue = HRMS_REPORT_SUN_DETAIL_InsertModel.DoubleValue,
                MapWithHRMS = HRMS_REPORT_SUN_DETAIL_InsertModel.MapWithHRMS
            };
            await _hRMS_REPORT_SUN_DETAIL.InsertRow(HRMS_REPORT_SUN_DETAIL_Model);
        }

        [HttpPatch("UpdateRow")]
        public async Task UpdateRow(HRMS_REPORT_SUN_DETAIL_ViewModel HRMS_REPORT_SUN_DETAIL_ViewModel)
        {
            HRMS_REPORT_SUN_DETAIL_Model HRMS_REPORT_SUN_DETAIL_Model = new HRMS_REPORT_SUN_DETAIL_Model()
            {
                Id = HRMS_REPORT_SUN_DETAIL_ViewModel.Id,
                SunAttribute = HRMS_REPORT_SUN_DETAIL_ViewModel.SunAttribute,
                IsConst = HRMS_REPORT_SUN_DETAIL_ViewModel.IsConst,
                AutoGenerated = HRMS_REPORT_SUN_DETAIL_ViewModel.AutoGenerated,
                ValueType = HRMS_REPORT_SUN_DETAIL_ViewModel.ValueType,
                StringValue = HRMS_REPORT_SUN_DETAIL_ViewModel.StringValue,
                IntValue = HRMS_REPORT_SUN_DETAIL_ViewModel.IntValue,
                ShortValue = HRMS_REPORT_SUN_DETAIL_ViewModel.ShortValue,
                DateTimeValue = HRMS_REPORT_SUN_DETAIL_ViewModel.DateTimeValue,
                DecimalValue = HRMS_REPORT_SUN_DETAIL_ViewModel.DecimalValue,
                DoubleValue = HRMS_REPORT_SUN_DETAIL_ViewModel.DoubleValue,
                MapWithHRMS = HRMS_REPORT_SUN_DETAIL_ViewModel.MapWithHRMS
            };
            await _hRMS_REPORT_SUN_DETAIL.UpdateRow(HRMS_REPORT_SUN_DETAIL_Model);
        }

        [HttpDelete("DeleteRow")]
        public async Task DeleteRow(int Id)
        {
            await _hRMS_REPORT_SUN_DETAIL.DeleteRow(Id);
        }


        [HttpPost("LoadDefaults")]
        public async Task LoadDefaults()
        {

            await _hRMS_REPORT_SUN_DETAIL.LoadDefaults();
        }
    }
}
