using ACT.DataModels;
using ACT.Services.ApiDbAccess.HRMS_SUN;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ACT.Controllers
{
    [ApiController]
    [Route("Mapping/HrmsToSun/ReportToHdr")]
    [EnableCors("MyPolicy")]
    public class Mapping_HRMS_REPORT_TO_SUN_HDR : ControllerBase
    {
        private IHRMS_REPORT_SUN_HDR _hRMS_REPORT_SUN_HDR;

        public class HRMS_REPORT_SUN_HDR_ViewModel
        {
            public int Id { get; set; }

            [Required]
            public string SunAttribute { get; set; }
            [Required]
            public bool IsConst { get; set; }
            [Required]
            public bool AutoGenerated { get; set; }
            [Required]
            public string ValueType { get; set; }
            public string StringValue { get; set; }
            public int? IntValue { get; set; }

            public short? ShortValue { get; set; }

            public DateTime? DateTimeValue { get; set; }

            public decimal? DecimalValue { get; set; }

            public double? DoubleValue { get; set; }

            public string MapWithHRMS { get; set; }
        }

        public Mapping_HRMS_REPORT_TO_SUN_HDR(IHRMS_REPORT_SUN_HDR hRMS_REPORT_SUN_HDR)
        {
            this._hRMS_REPORT_SUN_HDR = hRMS_REPORT_SUN_HDR;
        }

        [HttpGet("GetHrmsReportSunHdr")]
        public List<HRMS_REPORT_SUN_HDR_ViewModel> GetHrmsReportSunHdr()
        {
            List<HRMS_REPORT_SUN_HDR_ViewModel> HRMS_REPORT_SUN_HDR_ViewModels = new List<HRMS_REPORT_SUN_HDR_ViewModel>();

            foreach (HRMS_REPORT_SUN_HDR_Model o in _hRMS_REPORT_SUN_HDR.Get_HRMS_REPORT_SUN_HDR_s())
            {
                HRMS_REPORT_SUN_HDR_ViewModel HRMS_REPORT_SUN_HDR_ViewModel = new HRMS_REPORT_SUN_HDR_ViewModel()
                {
                    Id = o.Id,
                    SunAttribute = o.SunAttribute,
                    IsConst = o.IsConst,
                    AutoGenerated = o.AutoGenerated,
                    ValueType = o.ValueType,
                    StringValue = o.StringValue,
                    IntValue = o.IntValue,
                    ShortValue = o.ShortValue,
                    DateTimeValue = o.DateTimeValue,
                    DecimalValue = o.DecimalValue,
                    DoubleValue = o.DoubleValue,
                    MapWithHRMS = o.MapWithHRMS
                };
                HRMS_REPORT_SUN_HDR_ViewModels.Add(HRMS_REPORT_SUN_HDR_ViewModel);
            }

            return HRMS_REPORT_SUN_HDR_ViewModels;
        }

        [HttpPost("UpdateOperaReportSunHdr")]
        public async Task UpdateOperaReportSunHdr(List<HRMS_REPORT_SUN_HDR_ViewModel> HRMS_REPORT_SUN_HDR_ViewModels)
        {
            List<HRMS_REPORT_SUN_HDR_Model> hRMS_REPORT_SUN_HDR_s = new List<HRMS_REPORT_SUN_HDR_Model>();

            foreach (HRMS_REPORT_SUN_HDR_ViewModel o in HRMS_REPORT_SUN_HDR_ViewModels)
            {
                HRMS_REPORT_SUN_HDR_Model hRMS_REPORT_SUN_HDR = new HRMS_REPORT_SUN_HDR_Model()
                {
                    SunAttribute = o.SunAttribute,
                    IsConst = o.IsConst,
                    AutoGenerated = o.AutoGenerated,
                    ValueType = o.ValueType,
                    StringValue = o.StringValue,
                    IntValue = o.IntValue,
                    ShortValue = o.ShortValue,
                    DateTimeValue = o.DateTimeValue,
                    DecimalValue = o.DecimalValue,
                    DoubleValue = o.DoubleValue,
                    MapWithHRMS = o.MapWithHRMS
                };
                hRMS_REPORT_SUN_HDR_s.Add(hRMS_REPORT_SUN_HDR);
            }
            await _hRMS_REPORT_SUN_HDR.Update_HRMS_REPORT_SUN_HDR(hRMS_REPORT_SUN_HDR_s);
        }


        [HttpPost("LoadDefaults")]
        public async Task LoadDefaults()
        {

            await _hRMS_REPORT_SUN_HDR.LoadDefaults();
        }
    }
}
