using ACT.DataModels;
using ACT.Services.ApiDbAccess.HRMS_SUN;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ACT.Controllers
{
    [ApiController]
    [Route("Mapping/HrmsToSun/ReportToDetail")]
    [EnableCors("MyPolicy")]
    public class Mapping_HRMS_REPORT_TO_SUN_DETAIL : ControllerBase
    {
        private IHRMS_REPORT_SUN_DETAIL _hRMS_REPORT_SUN_DETAIL;

        public class HRMS_REPORT_SUN_DETAIL_ViewModel
        {
            public int Id { get; set; }

            [Required]
            public string SunAttribute { get; set; }
            [Required]
            public bool IsConst { get; set; }
            [Required]
            public bool AutoGenerated { get; set; }
            [Required]
            public string ValueType { get; set; }
            public string StringValue { get; set; }
            public int? IntValue { get; set; }

            public short? ShortValue { get; set; }

            public DateTime? DateTimeValue { get; set; }

            public decimal? DecimalValue { get; set; }

            public double? DoubleValue { get; set; }

            public string MapWithHRMS { get; set; }
        }

        public Mapping_HRMS_REPORT_TO_SUN_DETAIL(IHRMS_REPORT_SUN_DETAIL hRMS_REPORT_SUN_DETAIL)
        {
            this._hRMS_REPORT_SUN_DETAIL = hRMS_REPORT_SUN_DETAIL;
        }

        [HttpGet("GetHrmsReportSunDETAIL")]
        public List<HRMS_REPORT_SUN_DETAIL_ViewModel> GetHrmsReportSunDETAIL()
        {
            List<HRMS_REPORT_SUN_DETAIL_ViewModel> HRMS_REPORT_SUN_DETAIL_ViewModels = new List<HRMS_REPORT_SUN_DETAIL_ViewModel>();

            foreach (HRMS_REPORT_SUN_DETAIL_Model o in _hRMS_REPORT_SUN_DETAIL.Get_HRMS_REPORT_SUN_DETAIL_s())
            {
                HRMS_REPORT_SUN_DETAIL_ViewModel HRMS_REPORT_SUN_DETAIL_ViewModel = new HRMS_REPORT_SUN_DETAIL_ViewModel()
                {
                    Id = o.Id,
                    SunAttribute = o.SunAttribute,
                    IsConst = o.IsConst,
                    AutoGenerated = o.AutoGenerated,
                    ValueType = o.ValueType,
                    StringValue = o.StringValue,
                    IntValue = o.IntValue,
                    ShortValue = o.ShortValue,
                    DateTimeValue = o.DateTimeValue,
                    DecimalValue = o.DecimalValue,
                    DoubleValue = o.DoubleValue,
                    MapWithHRMS = o.MapWithHRMS
                };
                HRMS_REPORT_SUN_DETAIL_ViewModels.Add(HRMS_REPORT_SUN_DETAIL_ViewModel);
            }

            return HRMS_REPORT_SUN_DETAIL_ViewModels;
        }

        [HttpPost("UpdateOperaReportSunDETAIL")]
        public async Task UpdateOperaReportSunDETAIL(List<HRMS_REPORT_SUN_DETAIL_ViewModel> HRMS_REPORT_SUN_DETAIL_ViewModels)
        {
            List<HRMS_REPORT_SUN_DETAIL_Model> hRMS_REPORT_SUN_DETAIL_s = new List<HRMS_REPORT_SUN_DETAIL_Model>();

            foreach (HRMS_REPORT_SUN_DETAIL_ViewModel o in HRMS_REPORT_SUN_DETAIL_ViewModels)
            {
                HRMS_REPORT_SUN_DETAIL_Model hRMS_REPORT_SUN_DETAIL = new HRMS_REPORT_SUN_DETAIL_Model()
                {
                    SunAttribute = o.SunAttribute,
                    IsConst = o.IsConst,
                    AutoGenerated = o.AutoGenerated,
                    ValueType = o.ValueType,
                    StringValue = o.StringValue,
                    IntValue = o.IntValue,
                    ShortValue = o.ShortValue,
                    DateTimeValue = o.DateTimeValue,
                    DecimalValue = o.DecimalValue,
                    DoubleValue = o.DoubleValue,
                    MapWithHRMS = o.MapWithHRMS
                };
                       hRMS_REPORT_SUN_DETAIL_s.Add(hRMS_REPORT_SUN_DETAIL);
            }
            await _hRMS_REPORT_SUN_DETAIL.Update_HRMS_REPORT_SUN_DETAIL(hRMS_REPORT_SUN_DETAIL_s);
        }


        [HttpPost("LoadDefaults")]
        public async Task LoadDefaults()
        {

            await _hRMS_REPORT_SUN_DETAIL.LoadDefaults();
        }
    }
}
