using ACT.DataModels;
using ACT.DBContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ACT.Services.ApiDbAccess.OPERA_SUN
{
    public class OPERA_REPORT_SUN_DETAIL : IOPERA_REPORT_SUN_DETAIL
    {
        private ApiDbContext _apiDbContext;

        public OPERA_REPORT_SUN_DETAIL(ApiDbContext apiDbContext)
        {
            this._apiDbContext = apiDbContext;
        }

        public List<OPERA_REPORT_SUN_DETAIL_Model> Get_OPERA_REPORT_SUN_DETAIL_s()
        {
            return _apiDbContext.OPERA_REPORT_SUN_DETAILS.ToList();

        }

      
        public async Task Update_OPERA_REPORT_SUN_DETAIL(List<OPERA_REPORT_SUN_DETAIL_Model> oPERA_REPORT_SUN_DETAIL_s)
        {
            if (_apiDbContext.OPERA_REPORT_SUN_DETAILS.Count() > 0)
            {
                _apiDbContext.OPERA_REPORT_SUN_DETAILS.RemoveRange(_apiDbContext.OPERA_REPORT_SUN_DETAILS);
            }

            foreach (OPERA_REPORT_SUN_DETAIL_Model oPERA_REPORT_SUN_DETAIL_Model in oPERA_REPORT_SUN_DETAIL_s)
            {
                _apiDbContext.OPERA_REPORT_SUN_DETAILS.Add(oPERA_REPORT_SUN_DETAIL_Model);
            }

            await _apiDbContext.SaveChangesAsync();
        }

        public async Task LoadDefaults()
        {
            if (_apiDbContext.OPERA_REPORT_SUN_DETAILS.Count() > 0)
            {
                _apiDbContext.OPERA_REPORT_SUN_HDRS.RemoveRange(_apiDbContext.OPERA_REPORT_SUN_HDRS);
            }

            _apiDbContext.OPERA_REPORT_SUN_DETAILS.Add(new OPERA_REPORT_SUN_DETAIL_Model() { SunAttribute = "PSTG_HDR_ID", IsConst = false, AutoGenerated = true, ValueType = "int" });
            _apiDbContext.OPERA_REPORT_SUN_DETAILS.Add(new OPERA_REPORT_SUN_DETAIL_Model() { SunAttribute = "LINE_NUM", IsConst = false, AutoGenerated = true, ValueType = "int" });
            _apiDbContext.OPERA_REPORT_SUN_DETAILS.Add(new OPERA_REPORT_SUN_DETAIL_Model() { SunAttribute = "UPDATE_COUNT", IsConst = true, AutoGenerated = false, ValueType = "short", ShortValue = 0 });
            _apiDbContext.OPERA_REPORT_SUN_DETAILS.Add(new OPERA_REPORT_SUN_DETAIL_Model() { SunAttribute = "UPDATE_COUNT", IsConst = true, AutoGenerated = false, ValueType = "short", ShortValue = 0 });
            _apiDbContext.OPERA_REPORT_SUN_DETAILS.Add(new OPERA_REPORT_SUN_DETAIL_Model() { SunAttribute = "LAST_CHANGE_USER_ID", IsConst = true, AutoGenerated = false, ValueType = "string", StringValue = "OFS" });
            _apiDbContext.OPERA_REPORT_SUN_DETAILS.Add(new OPERA_REPORT_SUN_DETAIL_Model() { SunAttribute = "LAST_CHANGE_DATETIME", IsConst = true, AutoGenerated = false, ValueType = "string", StringValue = "GETDATE()" });
            _apiDbContext.OPERA_REPORT_SUN_DETAILS.Add(new OPERA_REPORT_SUN_DETAIL_Model() { SunAttribute = "ACNT_CODE", IsConst = false, AutoGenerated = false, ValueType = "string", MapWithOPERA= "GL" });
            _apiDbContext.OPERA_REPORT_SUN_DETAILS.Add(new OPERA_REPORT_SUN_DETAIL_Model() { SunAttribute = "PERD", IsConst = true, AutoGenerated = true, ValueType = "int" , MapWithOPERA="" });


        }

    }
}
